import Link from "next/link";
import { articles, visibleArticles } from "@/content/articles";
import { localizedHome, type SiteLocale } from "@/content/locales";
import { CellArt, Icon } from "./visuals";

export function LocalizedHome({ locale }: { locale: SiteLocale }) {
  const copy = localizedHome[locale];
  const featuredArticle = visibleArticles(articles)[0];
  const featuredHref = featuredArticle ? `/${locale}/articles/${featuredArticle.slug}/` : `/${locale}/articles/`;
  const categoryLinks = ["basics", "stem-cells", "treatment", "research"];
  return <div lang={locale === "en" ? "en" : "zh-CN"} className="localized-page">
    <>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span /> {copy.eyebrow}</div><h1>{copy.title[0]}<br />{copy.title[1]}<br /><em>{copy.title[2]}</em></h1><p>{copy.intro}</p><Link className="button primary" href={featuredHref}>{copy.start} <Icon name="arrow" size={20} /></Link><span className="hero-footnote">{copy.footnote}</span></div><div className="hero-visual"><CellArt hero label={locale === "en" ? "Abstract cell illustration" : "抽象细胞插画"} /><div className="visual-label"><span className="small-dot" /> LIFE, SCIENCE & YOU <span>{copy.visual}</span></div><div className="hero-floating"><Icon name="book" size={23} /><span>{copy.floating}<small>{copy.floatingSmall}</small></span></div></div></section>
    <section className="section purpose-section container"><div className="section-heading"><div><span className="eyebrow">START WITH A PURPOSE</span><h2>{locale === "en" ? "Find the right place to start." : "从目的开始寻找。"}<span className="heading-dot">.</span></h2></div><span className="section-caption">{locale === "en" ? "Choose the question closest to yours." : "从接近自己疑问的入口开始。"}</span></div><div className="purpose-links"><Link href={`/${locale}/guide/`}><strong>{locale === "en" ? "I want the basics" : "我想先了解基础"}</strong><span>{copy.guideLink} →</span></Link><Link href={`/${locale}/categories/treatment/`}><strong>{locale === "en" ? "I am considering treatment" : "我在考虑治疗"}</strong><span>{locale === "en" ? "Check safety, cost, and consent" : "确认安全性、费用与同意"} →</span></Link><Link href={`/${locale}/categories/research/`}><strong>{locale === "en" ? "I want to read research" : "我想阅读研究"}</strong><span>{locale === "en" ? "Understand stages and evidence" : "了解研究阶段与证据"} →</span></Link><Link href={`/${locale}/articles/questions-before-treatment/`}><strong>{locale === "en" ? "I want questions for my doctor" : "我想整理就诊问题"}</strong><span>{locale === "en" ? "Prepare before a consultation" : "在就诊前做好准备"} →</span></Link></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">{copy.topics}</span><h2>{copy.topicTitle}<span className="heading-dot">.</span></h2></div><span className="section-caption">{copy.topicCaption}</span></div><div className="category-grid">{copy.categories.map(([label, description], index) => <Link href={`/${locale}/categories/${categoryLinks[index]}/`} className={`category-card ${["green", "blue", "sand", "purple"][index]}`} key={label}><div className="category-top"><span className="category-icon"><Icon name={["cells", "network", "cross", "scope"][index]} size={31} /></span><span className="category-number">0{index + 1}</span></div><h3>{label}</h3><p>{description}</p><div className="category-bottom"><span>{["THE BASICS", "STEM CELLS", "YOUR CHOICES", "RESEARCH"][index]}</span><Icon name="arrow" size={21} /></div></Link>)}</div></section>
    <section className="feature-section"><div className="container feature"><div className="feature-art"><CellArt variant="network" label={locale === "en" ? "Abstract cell network illustration" : "抽象细胞ネットワークのイラスト"} /><span className="feature-caption">{copy.guideEyebrow}</span></div><div className="feature-copy"><span className="eyebrow">{copy.guideEyebrow}</span><h2>{copy.guideTitle}</h2><p>{copy.guideBody}</p><Link className="text-link" href={featuredHref}>{copy.guideLink} <span><Icon name="arrow" size={21} /></span></Link></div></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">THE JOURNAL</span><h2>{copy.journal}<span className="heading-dot">.</span></h2></div></div><div className="question-box"><div><span className="eyebrow">EDITORIAL PROMISE</span><p>{copy.promise}</p></div><Link className="button outline" href={featuredHref}>{copy.guideLink} <Icon name="arrow" size={19} /></Link></div></section>
    <p className="container disclaimer localized-disclaimer">{copy.disclaimer}</p>
    </>
  </div>;
}
