import Link from "next/link";
import { localizedHome, type SiteLocale } from "@/content/locales";
import { CellArt, Icon } from "./visuals";

export function LocalizedHome({ locale }: { locale: SiteLocale }) {
  const copy = localizedHome[locale];
  const categoryLinks = ["basics", "stem-cells", "treatment", "research"];
  return <>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span /> {copy.eyebrow}</div><h1>{copy.title[0]}<br />{copy.title[1]}<br /><em>{copy.title[2]}</em></h1><p>{copy.intro}</p><Link className="button primary" href={`/${locale}/articles/what-is-regenerative-medicine/`}>{copy.start} <Icon name="arrow" size={20} /></Link><span className="hero-footnote">{copy.footnote}</span></div><div className="hero-visual"><CellArt hero /><div className="visual-label"><span className="small-dot" /> LIFE, SCIENCE & YOU <span>{copy.visual}</span></div><div className="hero-floating"><Icon name="book" size={23} /><span>{copy.floating}<small>{copy.floatingSmall}</small></span></div></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">{copy.topics}</span><h2>{copy.topicTitle}<span className="heading-dot">.</span></h2></div><span className="section-caption">{copy.topicCaption}</span></div><div className="category-grid">{copy.categories.map(([label, description], index) => <Link href={`/${locale}/categories/${categoryLinks[index]}/`} className={`category-card ${["green", "blue", "sand", "purple"][index]}`} key={label}><div className="category-top"><span className="category-icon"><Icon name={["cells", "network", "cross", "scope"][index]} size={31} /></span><span className="category-number">0{index + 1}</span></div><h3>{label}</h3><p>{description}</p><div className="category-bottom"><span>{["THE BASICS", "STEM CELLS", "YOUR CHOICES", "RESEARCH"][index]}</span><Icon name="arrow" size={21} /></div></Link>)}</div></section>
    <section className="feature-section"><div className="container feature"><div className="feature-art"><CellArt variant="network" /><span className="feature-caption">{copy.guideEyebrow}</span></div><div className="feature-copy"><span className="eyebrow">{copy.guideEyebrow}</span><h2>{copy.guideTitle}</h2><p>{copy.guideBody}</p><Link className="text-link" href={`/${locale}/articles/what-is-regenerative-medicine/`}>{copy.guideLink} <span><Icon name="arrow" size={21} /></span></Link></div></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">THE JOURNAL</span><h2>{copy.journal}<span className="heading-dot">.</span></h2></div></div><div className="question-box"><div><span className="eyebrow">EDITORIAL PROMISE</span><p>{copy.promise}</p></div><Link className="button outline" href={`/${locale}/articles/what-is-regenerative-medicine/`}>{copy.guideLink} <Icon name="arrow" size={19} /></Link></div></section>
    <p className="container disclaimer localized-disclaimer">{copy.disclaimer}</p>
  </>;
}
